<div class="section">
  <div class="news">
    <h4 class="text-green">Les Sentiers Langeaisiens en questions...</h4>
    <h5 class="text-bg-green">Qui sommes-nous</h5>
    
    <img style="width: 250px; height: 151px; float: left;" src="<?php echo WEB_ROOT ?>img/association/01_accueil_grange.jpg" alt="" hspace="20"  vspace="30" />
    
    <p>
      Une association loi 1901 qui a pour but la sauvegarde des chemins ruraux de Langeais et des environs, le développement de la randonnée (pédestre, VTT, équestre), la création et l'entretien de circuits de randonnée. 
    </p>
    <p>Notre association est dirigée par un Conseil d'Administration d'une quinzaine de membres.</p>
    <p><font style="font-style: italic;" size="-1">La grange de l'Ile à Saint-Michel-sur-Loire</font>.</p>
    
    <h5 class="text-bg-green">Pourquoi une telle association à Langeais ?</h5>
          
    <p>La commune de Langeais compte de très nombreux chemins qui pour beaucoup traversent le massif forestier.
    <img style="width: 356px; height: 150px; float: right;" src="<?php echo WEB_ROOT ?>img/association/01_accueil_boeufs.jpg" alt="" hspace="5" /></p>
    <p>
      Avec le temps, certains de ces chemins ont disparu faute d'avoir été entretenus ou utilisés, d'autres sont fermés ou difficilement accessibles et les randonneurs (qu'ils soient à pied, à cheval ou à VTT) ont de plus en plus de difficultés pour trouver des chemins qui «sortent des sentiers battus».
    </p>
    <p>
      De plus, ces chemins constituent un patrimoine remarquable que nous nous devons de conserver pour les générations futures.
    </p>
    <h5 class="text-bg-green">Pour quoi faire ?</h5>
    <p>
      Faire l'inventaire des chemins existants.
      <br>
      Etablir un plan d'actions prioritaires à mener (liste des chemins à sauvegarder, remise en état, entretien).
      <br>
      Créer de nouveaux circuits balisés permanents et en faire assurer la promotion par différents moyens (associations, office de tourisme...).
    </p>

    <p>Pratiquer la randonnée pédestre ou VTT.</p>
    <p style="margin-bottom: 0cm;"><u>Toutes les activités de randonnée des Sentiers Langeaisiens<br><br></u></p>

    <table border="1" bordercolor="#000000" cellpadding="4" cellspacing="0" width="100%">
      <colgroup>
        <col width="38*" /> 
        <col width="100*" /> 
        <col width="118*" /> 
      </colgroup> 
      <thead> 
        <tr>
          <th width="15%">
            <p align="center">Activité</p>
          </th>
          <td valign="top" width="39%">
            <p align="center">Randonnée pédestre</p>
          </td>
          <td valign="top" width="46%">
            <p align="center">VTT</p>
          </td>
        </tr>
      </thead> 
      <tbody>
        <tr>
          <th width="15%">
            <p align="center">Public</p>
          </th>
          <td valign="top" width="39%">
            <p>Ouvert à tous (2€ non adhérents)</p>
          </td>
          <td valign="top" width="46%">
            <p>Réservé aux adhérents</p>
          </td>
        </tr>
        <tr>
          <th width="15%">
            <p align="center">Circuits proposés</p>
          </th>
          <td valign="top" width="39%">
            <p>Un de 10 km environ à allure modérée, un de 15 km
              environ à allure plus rapide</p>
          </td>
          <td valign="top" width="46%">
            <p>Deux groupes de niveau (30 à 50 km)</p>
          </td>
        </tr>
        <tr>
          <td width="15%">
            <p align="center"><i><b>Jour/Heure</b></i></p>
          </td>
          <td valign="top" width="39%">
            <p>Généralement le 3ème dimanche de chaque mois Départ à 9
              h </p>
          </td>
          <td valign="top" width="46%">
            <p>Chaque dimanche à 9 h heure d'hiver<br />
              et 8 h 30 heure d'été<br />
            </p>
          </td>
        </tr>
        <tr>
          <th width="15%">
            <p align="center">Lieu de départ</p>
          </th>
          <td valign="top" width="39%">
            <p>Le plus souvent du Parc des Loisirs, sauf pour les
              randonnées extérieures</p>
          </td>
          <td valign="top" width="46%">
            <p>Gymnase de l'école primaire sauf sorties extérieures</p>
          </td>
        </tr>
        <tr>
          <td rowspan="1" width="15%">
            <p align="center"><i><b>événements<br />
                </b></i></p>
          </td>
          <td valign="top" width="39%">
            <p>Sortie sur une journée ou 2 hors département réservée
              aux adhérents</p>
          </td>
          <td valign="top" width="46%">
            <p>Randonnée nocturne et sortie sur 2 jours hors
              département réservées aux adhérents</p>
          </td>
        </tr>
        <tr>
          <td rowspan="2" colspan="1" style="text-align: center; font-weight: bold; font-style: italic;">Organisations</td>
          <td rowspan="1" colspan="2" style="text-align: center;">Organisation de la Déval'Verte 
(randonnée pédestre et VTT ouverte à tous, le premier dimanche de mai)</td>
        </tr>
        <tr>
          <td rowspan="1" colspan="2" style="text-align: center;">Organisation de la Rando Gadoue
(randonnée pédestre et VTT ouverte à tous, le troisième  dimanche de novembre)</td>
        </tr>
      </tbody>
    </table>
    <h5 class="text-bg-green">Notre image</h5>
  
    <p>
      <img src="<?php echo WEB_ROOT ?>img/association/01_accueil_logoassociation.jpg" alt="" style="width: 227px; height: 155px; float: left;" hspace="20" vspace="20" />
      Le logo de l'association a été créé en 2009 par  Emilie Calbet designer infographiste et Maxime Désécot webmaster (<a href="mailto:maxetmili@gmail.com">maxetmili@gmail.com</a>). Ce logo répondait à une demande des adhérents VTTistes qui souhaitaient pouvoir être "reconnus", surtout dans les randos extérieures. 
    </p>
    <p>La section randonnée pédestre a profité de cette occasion pour bénéficier elle aussi d'un logo. </p>
    <p><img src="<?php echo WEB_ROOT ?>img/association/01_accueil_logovtt.jpg" alt="" style="width: 227px; height: 182px; float: right;" hspace="20" vspace="20" /></p>
    <p>
      Chaque section possède donc désormais son propre logo avec un logo commun pour l'association.
      <img src="<?php echo WEB_ROOT ?>img/association/01_accueil_logopedestre.jpg" alt="" style="width: 227px; height: 195px; float: left;" hspace="20" vspace="20" />
    </p>
    <p>
      Ces logos se veulent représentatifs de la vitalité de l'association (le marcheur et le VTTiste en action débordant le contour) ainsi que de son ancrage local (le pont de Langeais, la Loire et les éléments "nature"). 
    </p>
    <p>
      Ils permettent à l'association d'être plus facilement reconnue, de renforcer son image, et à chaque adhérent de porter sur lui un signe de reconnaissance dont il peut être fier !
    </p>

    <h5 class="text-bg-green">Pourquoi adhérer ? </h5>

    <p>
      Pour aider cette association (qui fonctionne sans subvention). Les seules ressources sont donc les adhésions.
      <br><br>
      Pour être informé des actions menées par l'association, être invité à y participer (au moins 2 courriers par adhérent dans
      l'année). <br>
      <img src="<?php echo WEB_ROOT ?>img/association/01_accueil_pedestre2.JPG" alt="" style="width: 400px; height: 242px; float: left;" hspace="20" vspace="20" /> 
      Pour pouvoir bénéficier du résultat des travaux de l'association (nouveaux sentiers ou circuits ouverts).<br><br>
      Pour avoir accès à la documentation mise à disposition des adhérents.<br><br>
      Pour rencontrer d'autres personnes intéressées par le mêmesujet.<br><br>
      Pour participer aux actions menées par l'association (randonnées, débroussaillage, reconnaissances de chemins...).
    </p>

    <h5 class="text-bg-green">Comment adhérer ?</h5>

    <p>En téléchargeant le bulletin suivant (format PDF ) :<img style="width: 245px; height: 150px; float: right;" src="<?php echo WEB_ROOT ?>img/association/01_accueil_loire.jpg" alt="" /></p>
    <p>
      <a target="_blank" href="telechargement/01_bulletin_adhesion_18-19_pedestre.pdf">Bulletin d'adhésion section pédestre</a>
    </p>
    <p>
      <a target="_blank" href="telechargement/01_bulletin_adhesion_18-19_VTT.pdf">Bulletin d'adhésion et règlement intérieur section VTT</a><br />
    </p>
    <p>Et en le renvoyant par courrier à l'adresse indiquée sur le bulletin, accompagné du montant de l'adhésion.</p>
    
    <h5 class="text-bg-green">Depuis quand ce site existe-t-il ?</h5>

    <p style="text-align: left;">Le site des Sentiers Langeaisiens a été mis en ligne le 8 juin 2005 par Yann Delalande, ancien responsable de la section VTT de l'association.</p>
    <p>Il a été réalisé avec des logiciels libres (Linux, Firefox, Kompozer).</p>
  </div>
</div>