<div class="section">
    <div class="news">
        <article>    
            <h3>Plus de 700 pour la 16ème Rando Gadoue</h3>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
            <p >Un beau soleil, des chemins humides mais pas boueux, tout ce qu'il fallait pour une randonnée facile au travers de superbes paysages d'automne.<br /></p>
            <p>
                <a href="gadoue.html">Compte-rendu à lire ici.</a>
            </p>
            <p >Photos en ligne pour le 25 novembre<br /></p>
        </article>
    </div>

    <div class="news">
        <h3>Les piétons dans la forêt de Tronçais</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Une superbe forêt de chênes, un peu de marche, des visites, un soleil généreux. La section pédestre a bénéficié de conditions idéales pour son week-end de fin d'année.<br /></p>
    </article>
    </div>
    <div class="news">
        <h3>Les VTTistes dans les monts d'Ambazac</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Un relief plus escarpé que la Touraine, des chemins très variés, avec quelques passages inondés, un ciel clément, des conditions parfaites pour un week-end qui restera gravé dans les mémoires.</p>
    </article>
    </div>
    <div class="news">
        <h3>Une Déval' Verte estivale, avec plus de 600 participants</h3>
        <article>
            <img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg">
            <p style="font-weight: normal;">Sous un soleil radieux, 417 VTTistes et 206 marcheurs ont pu profiter de conditions idéales pour découvrir les sous-bois langeaisiens.</p>
            
            <p>
                <a href="#">Photos en ligne. </a><br />
            </p>
            <p>
                <a href="devalverte.html">Compte-rendu de la randonnée.</a>
            </p> 
        </article>
    </div>
    <div class="news">
        <h3>Près de 850 participants à la Rando Gadoue : un nouveau record !</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">607 VTTistes, 239 piétons, peu de gadoue.<br></p>
        <p style="font-weight: normal;">Le brouillard suvi d'une pluie fine n'a pas entamé la bonne humeur des participants.</p>
        <p>
            <a href="gadoue.html">Compte-rendu</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="Rando%20Gadoue/Rando_Gadoue%202017/photos_gadoue2017.html">Page photos</a>
        </p>
        <p>Objets trouvés : voir compte-rendu</p>
    </article>
    </div>
    <div class="news">
        <h3>Langeais : chemin communal ou chemin privé ?</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Il n'est pas toujours facile de s'y retrouver ! <br /></p>
        <p style="font-weight: normal;">Quelques éléments de réponse dans la page "Circuits balisés" (descendre tout en bas de la page)</p>
    </article>
    </div>

</div>
