<div class="section">
    <div class="news">
        <h4 class="text-green">Liens divers et variés...</h4>
        <article>
        <h5 class="text-bg-green">VTT</h5>
        <h6 class="title">En Indre-et-Loire :</h6>
        <p class="text-margin-left">
        <img style="width: 225px; height: 300px;" class="img-news-right" alt="" src="<?php echo WEB_ROOT ?>img/liens/champignon.jpg">
            <a target="_blank" href="http://www.asfvtt.com/">Club de VTT de Fondettes :</a>
            des voisins avec un calendrier des randos très complet.
        </p>

        <p class="text-margin-left">
            <a href="http://batarami37.spaces.live.com/default.aspx" target="_blank">Espace Touraine VTT Bat 37 : </a>
            <span style="color: black;">un site rempli de compte-rendus de randos qui sentent le vécu ! Bonne analyse des randos décrites.</span>
        </p>
        <p class="text-margin-left">
            <a href="http://www.bourgueilvtt37.fr/" target="_blank">
            Club de Bourgueil : </a>site qui présente entre autres la rando "La Pente et Côte".
        </p>
        <p class="text-margin-left">
            <a href="http://www.cyclos-randonneurs-chinonais.org/7clochers/index.php" target="_blank">Ronde des 7 clochers :</a> 
            mini site présentant la rando organisée par les Cyclo Randonneurs Chinonais.
        </p>
        <p class="text-margin-left">
            <a href="http://sas-vtt.e-monsite.com/" target="_blank">SAS VTT :</a> le site des VTTistes de Saint-Avertin.<br />
        </p>
        <p class="text-margin-left">
            <a href="http://www.vettac.fr/">VETTAC</a>: site du club VTT d'Azay sur Cher. Présentation de la rando "l'Azayroise" et un calendrier agréable à lire.<br />
        </p>
        <h6 class="title">Ailleurs :</h6>
        <p class="text-margin-left">
            <a href="http://www.vetete.com/">vetete.com :</a>
            calendrier des randonnées VTT sur toute la France. Très complet, agréable à utiliser.
        </p>
        <p class="text-margin-left">
            <a target="_blank" href="http://www.vttfrance.com/">VTTFrance :</a>
            Calendrier des randonnées VTT sur toute la France, très utile. 
            <a href="http://www.vttfrance.com"></a>
        </p>

        <h5 class="text-bg-green">Marche</h5>

        <p class="text-margin-left"><a target="_blank" href="http://www.ffrandonnee.fr/">La Fédération Française de Randonnée</a></p>
        
        <p class="text-margin-left"><a target="_blank" href="http://www.cdrp37.fr/">Comité départemental de randonnée pédestre</a></p>
        
        <h5 class="text-bg-green">Divers</h5>
        
        <p class="text-margin-left">
            <a target="_blank" href="http://www.tourainenature.com/">Touraine Nature :</a>
            Informations touristiques et agenda des évenements sportifs et culturels.
        </p>
        <p class="text-margin-left">
            <a target="_blank" href="http://www.cen-centre.org/">Conservatoire du Patrimoine Naturel de la Région Centre :</a> 
            les actions du Conservatoire, le programme des balades nature.
        </p>
        </article>
    </div>
</div>