<div class="section">
    <div class="news">
        <h5 class="center-align"><b>Mentions légales</b></h5>
        <article>
        
        <p class="ml-size">
            <b><u>Propriétaire du site :</u></b> association loi 1901 "Les Sentiers Langeaisiens",<br>
        </p>
        <p class="ml-size">
            <b><u>siège social :</u></b> 66 allée des Quarts 37130 LANGEAIS<br>
        </p>
        <p class="ml-size">
        <b><u>Directeur de la publication et webmaster :</u></b> Jean-Marie DELALANDE
        </p>
        <p class="ml-size">
            <b><u>Contact :</u></b> sentierslangeaisiens@gmail.com<br>
        </p>
        <p class="ml-size"><b><u>Hébergeur :</u></b><br>
            AMEN<br>
            12 Rond-Point des Champs-Elysées<br>
            75008 PARIS<br>
        </p>
        <p class="ml-size">Pas de déclaration à la C.N.I.L. car le site ne conserve pas d'informations personnelles.</p>
        <p class="ml-size"><b><u>Traitement des données personnelles :</u></b><br>
            Les informations que l'association "Les Sentiers Langeaisiens" sera amenée à recueillir proviennent uniquement de l'enregistrement volontaire d'une adresse mail fournie par l'internaute, lui permettant de recevoir une documentation ou de se renseigner sur un point quelconque. Cette adresse n'est jamais communiquée à des tiers.
        </p>
    </div>




    </div>
</div>