<div class="section">
    <div class="news">
        <article>    
            <h3>16ème Rando Gadoue le 18 novembre</h3>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
            <p >Pour les amateurs de chemins humides, de sous-bois et de paysages d'automne, dans une ambiance conviviale, sans prise de tête. <br /></p>
            <p >Pensez à réserver votre dimanche !<br /></p>
        </article>
    </div>

    <div class="news">
        <h3>16ème Rando Gadoue le 18 novembre</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Pour les amateurs de chemins humides, de sous-bois et de paysages d'automne, dans une ambiance conviviale, sans prise de tête. <br /></p>
        <p style="font-weight: normal;">Pensez à réserver votre dimanche !</p>
    </article>
    </div>
    <div class="news">
        <h3>16ème Rando Gadoue le 18 novembre</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Pour les amateurs de chemins humides, de sous-bois et de paysages d'automne, dans une ambiance conviviale, sans prise de tête. <br /></p>
        <p style="font-weight: normal;">Pensez à réserver votre dimanche !</p>
    </article>
    </div>
    <div class="news">
        <h3>16ème Rando Gadoue le 18 novembre</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Pour les amateurs de chemins humides, de sous-bois et de paysages d'automne, dans une ambiance conviviale, sans prise de tête. <br /></p>
        <p style="font-weight: normal;">Pensez à réserver votre dimanche !</p>
    </article>
    </div>
    <div class="news">
        <h3>16ème Rando Gadoue le 18 novembre</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Pour les amateurs de chemins humides, de sous-bois et de paysages d'automne, dans une ambiance conviviale, sans prise de tête. <br /></p>
        <p style="font-weight: normal;">Pensez à réserver votre dimanche !</p>
    </article>
    </div>
    <div class="news">
        <h3>16ème Rando Gadoue le 18 novembre</h3>
        <article>
            <a href="#"><img class="img-news" alt="" src="<?php echo WEB_ROOT ?>img/news/gadoue2017.jpg"></a>
        <p style="font-weight: normal;">Pour les amateurs de chemins humides, de sous-bois et de paysages d'automne, dans une ambiance conviviale, sans prise de tête. <br /></p>
        <p style="font-weight: normal;">Pensez à réserver votre dimanche !</p>
    </article>
    </div>

</div>
